name: Testing
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-app:
    name: Test Application
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Test application
        run: go test ./...
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Extract short SHA
        id: vars
        run: echo "SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV        
      - name: Dry-run goreleaser application
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: ~> v2
          args: release --snapshot --skip=publish --clean
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SHA_SHORT: ${{ env.SHA_SHORT }}
          GITHUB_REPOSITORY: ${{ github.repository }}
