version: 2
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    tags:
      - netgo
    flags:
      - -trimpath
    ldflags:
      - -s -w -extldflags "-static"

dockers:
  - image_templates:
      - "docker.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Env.SHA_SHORT }}-amd64"
    goos: linux
    goarch: amd64
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }} version {{ .Version }}. See release notes at https://github.com/{{ .Env.GITHUB_REPOSITORY }}/releases/tag/v{{ .RawVersion }}"
      - "--label=org.opencontainers.image.url=https://github.com/{{ .Env.GITHUB_REPOSITORY }}"
      - "--label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_REPOSITORY }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - '--label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}'
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

  - image_templates:
      - "docker.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Env.SHA_SHORT }}-arm64"
    goos: linux
    goarch: arm64
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }} version {{ .Version }}. See release notes at https://github.com/{{ .Env.GITHUB_REPOSITORY }}/releases/tag/v{{ .RawVersion }}"
      - "--label=org.opencontainers.image.url=https://github.com/{{ .Env.GITHUB_REPOSITORY }}"
      - "--label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_REPOSITORY }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - '--label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}'
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

docker_manifests:
  - name_template: "docker.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Env.SHA_SHORT }}"
    image_templates:
      - "docker.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Env.SHA_SHORT }}-amd64"
      - "docker.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Env.SHA_SHORT }}-arm64"
  - name_template: "docker.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Major }}"
    image_templates:
      - "docker.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Env.SHA_SHORT }}-amd64"
      - "docker.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Env.SHA_SHORT }}-arm64"
  - name_template: "docker.io/{{ .Env.GITHUB_REPOSITORY }}:latest"
    image_templates:
      - "docker.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Env.SHA_SHORT }}-amd64"
      - "docker.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Env.SHA_SHORT }}-arm64"
