{{- $node_pool_id := .Values.node_pool_id | required ".Values.node_pool_id is required. Please provide this value with flag `--set node_pool_id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxxx`. To collect this value, select your cluster from the civo kubernetes dashboard, and use the copy next to your pool id. https://dashboard.civo.com/kubernetes" -}}
{{- $node_desired_gpu_count := .Values.node_desired_gpu_count | required ".Values.node_desired_gpu_count is required. Please provide this value with flag `--set node_desired_gpu_count=8" -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: kube-system
  labels:
    {{- include "node-agent.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "node-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "node-agent.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "node-agent.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: CIVO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: civo-api-access
                  key: api-key
            - name: CIVO_API_URL
              valueFrom:
                secretKeyRef:
                  name: civo-api-access
                  key: api-url
            - name: CIVO_CLUSTER_ID
              valueFrom:
                secretKeyRef:
                  name: civo-api-access
                  key: cluster-id
            - name: CIVO_REGION
              valueFrom:
                secretKeyRef:
                  name: civo-api-access
                  key: region
            - name: CIVO_NODE_POOL_ID
              value: {{ .Values.node_pool_id }}
            - name: CIVO_NODE_DESIRED_GPU_COUNT
              value: {{ .Values.node_desired_gpu_count }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-db-secret
                  key: password  
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
