{{- $civo_api_key := .Values.civo_api_key | required ".Values.civo_api_key is required. Please provide this value with flag `--set civo_api_key=8" -}}

apiVersion: v1
kind: Secret
metadata:
  name: civo-node-agent
  namespace: kube-system
type: Opaque
data:
  civo-api-key: {{ .Values.civo_api_key | b64enc }}
  node-pool-id: {{ .Values.node_pool_id | b64enc }}
  desired-gpu-count: {{ .Values.desired_gpu_count | b64enc }}
  