apiVersion: v2
name: node-agent
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0-rc.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v0.1.0"





{"time":"2025-03-01T08:57:36.23950288Z","level":"ERROR","msg":"The node-agent encountered a critical error and will exit","clusterID":"4f9d00d8-3f4a-41cc-9ca9-30f3710e0564","region":"nyc1","nodePoolID":"b62a8764-b4e9-4654-a2c3-7ef196749afa","error":"failed to intiliase civo client: NoAPIKeySuppliedError: no API Key supplied, this is required"}
stream closed EOF for kube-system/node-agent-66d686bbb-wbpk5 (node-agent)
