replicaCount: 1


image:
  repository: jokesta/na
  pullPolicy: IfNotPresent
  tag: "0.17"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
resources: {}


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

## your node_pool_id value can be found in the the civo kubernetes dashboard
## https://dashboard.civo.com/kubernetes
## choose your cluster, then click the copy link next to the node pool id
node_pool_id: 

## this value is intended to match the number of GPUs per node. 
## if you had a 2-node cluster with 8 GPU total, you would set this value to 4 to represent the number of GPOs per node.
desired_gpu_count:

## your civo api key
## https://dashboard.civo.com/security
civo_api_key:
